# Path: src/config/builder_config.yaml

suttacentral-sqlite:
  path: "data/processed"
  name: suttacentral.sqlite
  # Hierarchy
  bibliography: "data/raw/git/sc-data/additional-info/biblio.json"
  tree: 
    - super-tree: "data/raw/git/sc-data/structure/tree/super-tree.json"
    - sutta: "data/raw/git/sc-data/structure/tree/sutta"
    - vinaya: "data/raw/git/sc-data/structure/tree/vinaya"
    - abhidhamma: "data/raw/git/sc-data/structure/tree/abhidhamma"
    - ignore:
        - upp-tree.json
  suttaplex: 
    data: "data/processed/prebuild/suttaplex-json/suttaplex.json"
    translation_files:
      json_segment:
        path: "data/processed/prebuild/bilara/sc_bilara_segments.json"
        groups: [root, translation]
      html_text: 
        path: "data/processed/prebuild/sc_html_text_authors.json"
    blurb_supplement:
      - data/raw/supplement/blurb_supplement.tsv
  bilara-segment:
    folder: "data/raw/git/sc-data"
    json: 
      - Bilara_names: "data/processed/prebuild/bilara/sc_names.json"
      - Bilara_blurbs: "data/processed/prebuild/bilara/sc_blurbs.json"
      - Bilara_sites: "data/processed/prebuild/bilara/sc_sites.json"
      - Bilara_segments: "data/processed/prebuild/bilara/sc_bilara_segments.json"
    author-remap:
      sutta: null
