# Path: src/config/builder_config.yaml

suttacentral-sqlite:
  path: "data/processed"
  name: suttacentral.sqlite
  # Hierarchy
  bibliography: "data/raw/git/suttacentral-data/additional-info/biblio.json"
  tree: 
    - super-tree: "data/raw/git/suttacentral-data/structure/tree/super-tree.json"
    - sutta: "data/raw/git/suttacentral-data/structure/tree/sutta"
    - vinaya: "data/raw/git/suttacentral-data/structure/tree/vinaya"
    - abhidhamma: "data/raw/git/suttacentral-data/structure/tree/abhidhamma"
    - ignore:
        - upp-tree.json
  suttaplex: 
    data: "data/raw/suttaplex/suttaplex.json"
    translation_files:
      json_segment:
        path: "data/raw/git/sc_bilara.json"
        groups: [root, translation]
      html_text: 
        path: "data/raw/git/sc_html_text_authors.json"
    blurb_supplement:
      - data/raw/supplement/blurb_supplement.tsv
  bilara-segment:
    folder: "data/raw/git/suttacentral-data"
    json: 
      - Segments_bilara: "data/raw/git/sc_bilara.json"
      - Segments_site: "data/raw/git/sc_site.json"
    author-remap:
      sutta: null
