# Path: src/config/builder_config.yaml

suttacentral-sqlite:
  path: "data/processed"
  name: suttacentral.sqlite
  # Hierarchy
  bibliography: "data/raw/git/suttacentral-data/additional-info/biblio.json"
  tree: 
    - super-tree: "data/raw/git/suttacentral-data/structure/tree/super-tree.json"
    - sutta: "data/raw/git/suttacentral-data/structure/tree/sutta"
    - vinaya: "data/raw/git/suttacentral-data/structure/tree/vinaya"
    - abhidhamma: "data/raw/git/suttacentral-data/structure/tree/abhidhamma"
    - ignore:
        - upp-tree.json
  suttaplex: 
    - data: "data/raw/suttaplex"
    - blurb: "data/raw/git/suttacentral-data/sc_bilara_data/root/en/blurb"
  bilara: "to be done"