# Path: src/config/updater_config.yaml

git:
  sub-submodule:
    - cips: https://github.com/thesunshade/CIPS
    - suttacentral-data: https://github.com/suttacentral/sc-data
release:
  git-release:
    dpd:
      link: https://github.com/digitalpalidictionary/dpd-db
      version: latest
      assets: 
        - name: dpd-kindle.epub
          extract: true
          extract_to_folder: true
        - dpd.db.tar.bz2
buddha-words:
  google-drive:
    zip: https://drive.google.com/drive/folders/17DZmO3PaN_bXPyDuQGRkX4dcYQ0tXhe8
    version-date: '(?:bw)(\d+)\.(?:7z|zip)$'
    extract: "bw"
suttaplex:
  api:
    base_url: "https://suttacentral.net/api/suttaplex/"
    # --- ĐÃ CẬP NHẬT SANG ĐỊNH DẠNG MỘT DÒNG ---
    groups:
      sutta: [sutta]
      vinaya: [vinaya]
      abhidhamma: [abhidhamma]
      sutta-update: [sn]
# dhammatalks:
#   crawl:
#     - bmc: https://www.dhammatalks.org/vinaya/bmc/Section0000.html
#       root: https://www.dhammatalks.org/vinaya/bmc
#     - suttas: https://www.dhammatalks.org/suttas/
#       root: https://www.dhammatalks.org/suttas
